---
kind: pipeline
name: default

steps:
  - name: 'build 18.04'
    image: plugins/docker
    settings:
      repo: glyx/ubuntu-systemd
      dockerfile: Dockerfile.18.04
      tags: [latest, '18.04']
      username: glyx
      password:
        from_secret: docker-hub

  - name: 'build 16.04'
    image: plugins/docker
    settings:
      repo: glyx/ubuntu-systemd
      dockerfile: Dockerfile.16.04
      tags: '16.04'
      username: glyx
      password:
        from_secret: docker-hub

trigger:
  branch:
  - master
